name: A simple CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: install fyne
        run: brew instal fyne
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: list-again
        run: ls -alh
      - name: make
        run: make darwin
      
      
